### ISSUE TITLE
Reboot after a while release 1.01

### ISSUE THREAD

**Issue by ZinhoRacing** [mistyk/inavradar-ESP32#11]
Hi @KingKone,
I'm testing new release 1.01 and first of all, that's an impressive work :smiley:

I'm using the modules specified in the hardware section (Banggood 868MHz).

What I see is after some minutes the unit is rebooting. 
I'm using 4 units to test, all ok and then they reboot some times, not at the same moment but all of them do. I'm doing it on the bench, no FC connected to any unit. All units powered from my laptop (4 independant USB port, no hub).

**Comment by KingKone** [comment]
Oh ok, all 4 modules the same behavior? 

Could you specify 'some minutes'? 
More like 10 or 5 minutes?

I will send that to Olivier.

**Comment by OlivierC-FR** [comment]
I recall I had such reboots some time ago during tests, but that was on the stats page I think, the one that shows the timings for the nodes. Maybe a memory leak or corruption there. Do you remember what display page it was when it happened ?

**Comment by KingKone** [comment]
could you keep a serial terminal open on you laptop, ans paste the output after the crash?

**Comment by OlivierC-FR** [comment]
I added an uptime in seconds, and let it run for at least 20 minutes on pages 0, 1 and 2, and did not get any reboot. I compared with a timer on my phone to make sure it wasn't rebooting while I was away.
I'll keep an eye on this

![20190509_150556](https://user-images.githubusercontent.com/25566932/57455842-62bb7e80-726c-11e9-879c-611fc6e0756b.jpg)
![20190509_150538](https://user-images.githubusercontent.com/25566932/57455844-63541500-726c-11e9-9df5-f9ce95cf9381.jpg)

**Comment by ZinhoRacing** [comment]
Hello. I’ll try to log serial tonight.
I don’t remember if i was on the same page on all the units. I’ll pay more attention tonight.

**Comment by ZinhoRacing** [comment]
I think i got one. 

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:812
load:0x40078000,len:0
load:0x40078000,len:11584
entry 0x40078a60
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:1445 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088553 on core 1

Backtrace: 0x40085e14:0x3ffbe820 0x40086041:0x3ffbe840 0x40088553:0x3ffbe860 0x400d6ad9:0x3ffbe8a0 0x400d487d:0x3ffbe8c0 0x400d1088:0x3ffbe8f0 0x400d10bc:0x3ffbe910 0x400d1711:0x3ffbe930 0x400d176a:0x3ffbe950 0x40080f25:0x3ffbe970 0x40081e25:0x3ffbe990 0x40089999:0x00000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:812
load:0x40078000,len:0
load:0x40078000,len:11584
entry 0x40078a60
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:1445 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088553 on core 1

Backtrace: 0x40085e14:0x3ffbe820 0x40086041:0x3ffbe840 0x40088553:0x3ffbe860 0x400d6ad9:0x3ffbe8a0 0x400d487d:0x3ffbe8c0 0x400d1088:0x3ffbe8f0 0x400d10bc:0x3ffbe910 0x400d1711:0x3ffbe930 0x400d176a:0x3ffbe950 0x40080f25:0x3ffbe970 0x40081e25:0x3ffbe990 0x4000bfed:0x00000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:812
load:0x40078000,len:0
load:0x40078000,len:11584
entry 0x40078a60

**Comment by ZinhoRacing** [comment]
Another one. After a reboot. I was playing with 4 units standard mode and 1 more in silent mode. 
![IMG_1708](https://user-images.githubusercontent.com/41761785/57486879-5efd1b80-72af-11e9-94fc-9afdba5b2984.jpg)

**Comment by OlivierC-FR** [comment]
This code is not what I run on my modules, I have nothing RTOS in there, neither CLI.
What is the release built from, the master branch ?

**Comment by OlivierC-FR** [comment]
Did you get the firmware from the zip packages, or did you build it yourself from the master branch within the last 2 days ?

**Comment by ZinhoRacing** [comment]
Hi,
I'm using the code from the zip package air-2-air-868-1.01.zip from last 2 days. Not buiding it.

**Comment by KingKone** [comment]
try 1.2 hope its better, we have an installer now =D

**Comment by ZinhoRacing** [comment]
1.21 tested Ok :smiley: no reboot seen so far. (868Mhz modules)
I like the Logo :smiley:

Would it be possible to go to host page when armed and only switch off display when alt is greater than threshold ( 10m for exemple). As it is great to see Vbat and mAh, Sat num when on the ground.

My setup below, cularis moto glider, I cut a window to see the display on the side (with old version of Inav Radar).

![image](https://user-images.githubusercontent.com/41761785/57809627-21443b00-7766-11e9-8eb0-0a32fce584cf.png)

**Comment by KingKone** [comment]
you have compiled it yourself?
we have some bug in 1.2 and 1.21 too i think, so please don't fly, 
FC will overoad.

**Comment by ZinhoRacing** [comment]
Yes. I have atom and plateformio. Ok no problem I’ll only test on the bench. Thanks.

**Comment by OlivierC-FR** [comment]
@ZinhoRacing I pushed the 1.30 few minutes ago, with some important tweaks, and also the iNav side appears to be more stable, at least on the bench. I launched the build for all iNav targets, will then put it on the dropbox same as usual.

**Comment by ZinhoRacing** [comment]
Merci @OlivierC-FR I’ll have a go tonight.

**Comment by KingKone** [comment]
seems to be fixed in new versions
