### ISSUE TITLE
Closer integration/cooperation with INAV

### ISSUE THREAD

**Issue by digitalentity** [mistyk/inavradar-ESP32#2]
We need to cooperate closer on this project. Looping also @DzikuVx, @fiam

**Comment by KingKone** [comment]
Yes i think so too, nice to hear from you! 
I thought we are not ready yet to bother you ...

its all a bit messy right now ..

**Comment by KingKone** [comment]
Camille and I have no real experience in doing something like this, we played around with mcus but not something at this scale

**Comment by digitalentity** [comment]
@fiam is working on "flock" support for INAV, the only thing we need is hardware to exchange coordinates between UAVs (and a "standardized" way of doing it)

**Comment by digitalentity** [comment]
Messy or not - let's get it working first. We can cleanup and refactor it later.

**Comment by KingKone** [comment]
the lora modems are very nice, somebody in the goup also found very small ones without display .. but have you and info about flock, so i can learn what that is

**Comment by mistyk** [comment]
Thanks to you, we keep in touch when first release will available , to merge with inav we have some functions to redraw because we are not expert on inav ;)
