### ISSUE TITLE
iNAV-Radar UAV Arrow Behavior

### ISSUE THREAD

**Issue by badandy1223** [mistyk/inavradar-ESP32#4]
Have the Arrow's behavior selectable in the CLI in 3 modes:
OFF- Arrow does not appear in the OSD
ROTATE - Arrow rotates to the direction of the nearest UAV (doesn't matter if 1 or 6 UAV's are flying, ALWAYS the closest.)
FIXED - Arrow does not rotate. Fixed pointing up on the screen.

**Comment by noagendafpv** [comment]
Also make the "this plane" arrow a plane symbol with edited Font files for the fixed indicator.
