### ISSUE TITLE
Speed indicator doesn't work

### ISSUE THREAD

**Issue by 4stralay** [mistyk/inavradar-ESP32#5]
On the image show below... the speed indicator show 0 Km/hr. 
The iNav firmware  was given by Camile in Facebook messenger for Matek F405SE (Matek F405 Wing)

![0 speed](https://user-images.githubusercontent.com/45894813/52837093-bdba5b00-30ed-11e9-9f7f-f8f2191b65f8.png)

On the image below the speed indicator does work.
iNav firmware was INAV-Radar 0.1-alpha3 for Matek F405 (Matek F405 CTR)

![ok speed](https://user-images.githubusercontent.com/45894813/52837345-a16aee00-30ee-11e9-98ca-bc290889253b.png)

**Comment by mistyk** [comment]
Regression due to "Miles unity" bugfix.. removing Miles for the next to verify that

**Comment by KingKone** [comment]
Seems to work in my last test.
Leave it open till Metric - Imperial is fixed

**Comment by noagendafpv** [comment]
https://www.youtube.com/watch?v=6bWrJzgyxeY

Worked on my ground test unit, with speed from flying module updating. MatekF722SE Alpha5 on the plane, and MatekF405SE Alpha5.1 on the ground test unit. Both have 915mhz LoRa modules on Alpha5 FW.
