### ISSUE TITLE
Splash screen with Inav Radar logo

### ISSUE THREAD

**Issue by ZinhoRacing** [mistyk/inavradar-ESP32#9]
Hi,
While playing with the code, I have made a splash screen if you interested I can give it to you @KingKone.
It looks nice on the little display 😄 (and I agree it's not big deal and bit useless but cool 😄 )

![IMG_1694](https://user-images.githubusercontent.com/41761785/56789828-2a935500-6803-11e9-8e92-661f280cfef2.jpg)

**Comment by KingKone** [comment]
wow nice, i like useless but cool things

**Comment by ZinhoRacing** [comment]
Here is the code.

```
// Include
#include "inavradarlogo.h"

//  in void InitDisplay() procedure just after display.flipScreenVertically ();

 display.clear();
 display.drawXbm(0, 0, logo_width_s, logo_height_s, logo_bits_s);
 display.display();
 delay(2000);

```

That's all :smile:

[inavradarlogo.zip](https://github.com/mistyk/inavradar-ESP32/files/3122199/inavradarlogo.zip)

**Comment by KingKone** [comment]
Thank you! What converter did u use for the picture?

**Comment by ZinhoRacing** [comment]
I used a online converter tool : https://www.online-utility.org/image/convert/to/XBM
That's the only one that worked for me.
